April9/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'happy/abc'

  get 'welcome/index'
 resources :articles do
 	resources :products
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

April9/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

April9/app/models/article.rb
class Article < ApplicationRecord
has_many :products
validates :title, presence: true,
                    length: { minimum: 5 }
validates :text, presence: true,
                    length: { minimum: 6 }
end

April9/app/models/product.rb
class Product < ApplicationRecord
belongs_to :article
end

April9/app/models/third.rb
class Third < ApplicationRecord
end

April9/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

April9/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
 def new 
  @article =Article.new
 end
 

 def create 
render plain:params[:article].inspect
 end
 

 def edit
  @article = Article.find(params[:id])
end

def create
  @article = Article.new(article_params)
 
 if @article.save
  redirect_to @article
else 
  render 'new'
end
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end
def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end
 private
   def article_params
    params.require(:article).permit(:title, :text ,:pin)
   end
end

April9/app/controllers/code_controller.rb
class CodeController < ApplicationController
end

April9/app/controllers/happy_controller.rb
class HappyController < ApplicationController
  def abc
  end
end

April9/app/controllers/products_controller.rb
class ProductsController < ApplicationController

# def create
	
# 	render plain: params[:product_params].inspect
# 	 end
def create
    @article = Article.find(params[:article_id])
    @product = @article.products.create(product_params)
    redirect_to article_path(@article)
  end
 
  private
    def product_params
      params.require(:product).permit(:Name, :Info, :Quantitiy)
    end
end

April9/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

April9/app/helpers/application_helper.rb
module ApplicationHelper
end

April9/app/helpers/articles_helper.rb
module ArticlesHelper
end

April9/app/helpers/code_helper.rb
module CodeHelper
end

April9/app/helpers/happy_helper.rb
module HappyHelper
end

April9/app/helpers/products_helper.rb
module ProductsHelper
end

April9/app/helpers/welcome_helper.rb
module WelcomeHelper
end

April9/app/views/articles/_forms.html.erb
<%= form_with model: @article,local: true do |form| %>
   <% if @article.errors.any? %>
       
        <div id="error_explanation">
        
          <h2>
             <%= pluralize(@article.errors.count, "error") %> prohibited
              this article from being saved:
          </h2>
       <ul>
 <% @article.errors.full_messages.each do |msg| %>

          <li><%= msg %></li>
        <% end %>
         </ul>
         </div>
  <% end %>
   


   <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  

   <p>
    <%= form.label :Pin %><br>
    <%= form.text_area :pin %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

April9/app/views/articles/edit.html.erb
<hi>edit aricle</hi>
<%= render 'forms' %>

April9/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>

  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Pin</th>
  </tr>

  <%= link_to 'New Item', new_article_path %>
 
  <% @articles.each do |article| %>
    <tr>
     
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.pin %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
   
        <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>s
    </tr>
  <% end %>

</table>

      <h1>Hello, Rails!</h1>
      <%= form_with scope: :article, url: articles_path, local: true do |form| %>
  
   <% end %>
 
      <%= link_to 'Back', articles_path %>

April9/app/views/articles/new.html.erb
<hi>new aricle</hi>
<%= render 'forms' %>

April9/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @article.pin %>
</p>

<h2>Products</h2>
<% @article.products.each do |product| %>
  <p>
    <strong>Name:</strong>
    <%= product.Name%>
  </p>
 
  <p>
    <strong>Info:</strong>
    <%= product.Info %>
  </p>
<p>
    <strong>Quantitiy:</strong>
    <%= product.Quantitiy %>
  </p>

<% end %>


<h2>Add a product:</h2>
   
   <%= form_with(model: [ @article, @article.products.build ]) do |form| %> 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>

  <p>
    <%= form.label :Info %><br>
    <%= form.text_area :Info %>
  </p>

  <p>
    <%= form.label :Quantitiy %><br>
    <%= form.number_field :Quantitiy %>
   
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

April9/app/views/happy/abc.html.erb
<h1>Happy#abc</h1>
<p>Find me in app/views/happy/abc.html.erb</p>

April9/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>April3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

April9/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>